In [1]:
import os, sys
print(os.getcwd())   # dónde está parado el notebook
print(sys.path)      # lista de rutas donde busca módulos
print(os.listdir())  # qué archivos hay en el directorio actual
import sys, os

# Aseguramos que el directorio del notebook esté en sys.path
project_path = os.path.dirname(os.path.abspath("intro.ipynb"))
if project_path not in sys.path:
    sys.path.append(project_path)

print("Ruta agregada:", project_path)
import eda
import main
import consulta_SQL
import polars as pl

c:\Users\Flor\Projects\DM_EyF
['C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\python311.zip', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\DLLs', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\\Lib', 'C:\\Program Files\\WindowsApps\\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0', 'c:\\Users\\Flor\\Projects\\DM_EyF\\env_test', '', 'c:\\Users\\Flor\\Projects\\DM_EyF\\env_test\\Lib\\site-packages', 'c:\\Users\\Flor\\Projects\\DM_EyF\\env_test\\Lib\\site-packages\\win32', 'c:\\Users\\Flor\\Projects\\DM_EyF\\env_test\\Lib\\site-packages\\win32\\lib', 'c:\\Users\\Flor\\Projects\\DM_EyF\\env_test\\Lib\\site-packages\\Pythonwin']
['.git', '.gitignore', 'competencia_01_con_clase_ternaria.csv', 'competencia_01_crudo.csv', 'consulta_SQL.py', 'df_abril.csv', 'df_confe.csv', 'eda.py', 'env_test', 'intro.ipynb', 'main.py', 'modelo.ipynb', 'requirements.txt', 'schema.json', 'test.ipynb', '__pycache__']
Ruta agregada: c:\Users\Flor\Projects\DM_EyF
shape: (5, 155)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag ┆ clase_ter │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumos     ┆ lantosefe ┆ ominimo   ┆ naria     │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ctivo     ┆ ---       ┆ ---       │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ f64       ┆ str       │
│           ┆          ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 249221323 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ 6         ┆ 0         ┆ 9559.95   ┆ CONTINUA  │
│ 249221323 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ 8         ┆ 0         ┆ 7413.36   ┆ CONTINUA  │
│ 249221323 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ 7         ┆ 0         ┆ 0.0       ┆ CONTINUA  │
│ 249221323 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ 6         ┆ 0         ┆ 0.0       ┆ CONTINUA  │
│ 249221323 ┆ 202105   ┆ 1         ┆ 0         ┆ … ┆ 6         ┆ 0         ┆ 2111.4    ┆ CONTINUA  │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (5, 155)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag ┆ clase_ter │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumos     ┆ lantosefe ┆ ominimo   ┆ naria     │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ctivo     ┆ ---       ┆ ---       │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ f64       ┆ str       │
│           ┆          ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 159836843 ┆ 202106   ┆ 1         ┆ 0         ┆ … ┆ 2         ┆ 0         ┆ 1747.77   ┆ CONTINUA  │
│ 3         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 159841941 ┆ 202106   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ CONTINUA  │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 159842590 ┆ 202106   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ CONTINUA  │
│ 5         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 159847038 ┆ 202106   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ CONTINUA  │
│ 9         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 159855016 ┆ 202106   ┆ 0         ┆ 0         ┆ … ┆ null      ┆ null      ┆ 0.0       ┆ CONTINUA  │
│ 7         ┆          ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (5, 155)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag ┆ clase_ter │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumos     ┆ lantosefe ┆ ominimo   ┆ naria     │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ctivo     ┆ ---       ┆ ---       │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ f64       ┆ str       │
│           ┆          ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 249221323 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ 6         ┆ 0         ┆ 9559.95   ┆ CONTINUA  │
│ 249221323 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ 8         ┆ 0         ┆ 7413.36   ┆ CONTINUA  │
│ 249221323 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ 7         ┆ 0         ┆ 0.0       ┆ CONTINUA  │
│ 249221323 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ 6         ┆ 0         ┆ 0.0       ┆ CONTINUA  │
│ 249221323 ┆ 202105   ┆ 1         ┆ 0         ┆ … ┆ 6         ┆ 0         ┆ 2111.4    ┆ CONTINUA  │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘
shape: (6, 4)
┌──────────┬──────────┬────────┬────────┐
│ foto_mes ┆ CONTINUA ┆ BAJA+2 ┆ BAJA+1 │
│ ---      ┆ ---      ┆ ---    ┆ ---    │
│ i64      ┆ u32      ┆ u32    ┆ u32    │
╞══════════╪══════════╪════════╪════════╡
│ 202101   ┆ 160087   ┆ 824    ┆ 616    │
│ 202102   ┆ 160298   ┆ 1027   ┆ 830    │
│ 202103   ┆ 161122   ┆ 953    ┆ 1034   │
│ 202104   ┆ 161333   ┆ 1131   ┆ 954    │
│ 202105   ┆ 162783   ┆ 0      ┆ 1134   │
│ 202106   ┆ 164313   ┆ 0      ┆ 0      │
└──────────┴──────────┴────────┴────────┘

In [2]:
# Supongamos que el archivo se llama "datos.csv"
df = pl.read_csv("competencia_01_con_clase_ternaria.csv")

In [3]:
import polars as pl
# Mostrar todos los registros del cliente 930544172
cliente_id = 930544172

df_cliente = df.filter(pl.col("numero_de_cliente") == cliente_id)

print(df_cliente)

shape: (2, 155)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag ┆ clase_ter │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumos     ┆ lantosefe ┆ ominimo   ┆ naria     │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ctivo     ┆ ---       ┆ ---       │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ i64       ┆ ---       ┆ f64       ┆ str       │
│           ┆          ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 930544172 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ 11        ┆ 0         ┆ 1137.81   ┆ BAJA+2    │
│ 930544172 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ 9         ┆ 0         ┆ 1794.69   ┆ BAJA+1    │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
ganancia_acierto = 780000
costo_estimulo = 20000

In [5]:
data = df.filter(pl.col('foto_mes') == 202104)

X = data.drop('clase_ternaria')
y = data['clase_ternaria']

In [6]:
tabla_valores = (
    data["clase_ternaria"]
    .value_counts(normalize=True)
    .with_columns(
        (pl.col("proportion") * 100).alias("porcentaje")
    )
)

print(tabla_valores)

shape: (3, 3)
┌────────────────┬────────────┬────────────┐
│ clase_ternaria ┆ proportion ┆ porcentaje │
│ ---            ┆ ---        ┆ ---        │
│ str            ┆ f64        ┆ f64        │
╞════════════════╪════════════╪════════════╡
│ BAJA+1         ┆ 0.005838   ┆ 0.583779   │
│ CONTINUA       ┆ 0.987241   ┆ 98.724131  │
│ BAJA+2         ┆ 0.006921   ┆ 0.69209    │
└────────────────┴────────────┴────────────┘

In [7]:
# Supongamos que tu DataFrame se llama df
# Detectar automáticamente columnas numéricas
numeric_cols = [
    col for col, dtype in df.schema.items()
    if dtype in [pl.Int8, pl.Int16, pl.Int32, pl.Int64, pl.Float32, pl.Float64]
]

# Agregar columnas de min y max por cliente usando over
df_final = df.with_columns([
    pl.min(col).over("numero_de_cliente").alias(f"{col}_min") for col in numeric_cols
] + [
    pl.max(col).over("numero_de_cliente").alias(f"{col}_max") for col in numeric_cols
])

df_final.head(10)

shape: (10, 459)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_mcon ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumototal ┆ sumos_max ┆ lantosefe ┆ ominimo_m │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ _max      ┆ ---       ┆ ctivo_max ┆ ax        │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ ---       ┆ i64       ┆ ---       ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆           ┆ i64       ┆ f64       │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 249221323 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ 16101.68  ┆ 8         ┆ 0         ┆ 9559.95   │
│ 249221323 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ 16101.68  ┆ 8         ┆ 0         ┆ 9559.95   │
│ 249221323 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ 16101.68  ┆ 8         ┆ 0         ┆ 9559.95   │
│ 249221323 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ 16101.68  ┆ 8         ┆ 0         ┆ 9559.95   │
│ 249221323 ┆ 202105   ┆ 1         ┆ 0         ┆ … ┆ 16101.68  ┆ 8         ┆ 0         ┆ 9559.95   │
│ 249221323 ┆ 202106   ┆ 1         ┆ 0         ┆ … ┆ 16101.68  ┆ 8         ┆ 0         ┆ 9559.95   │
│ 249227600 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ 11947.53  ┆ 10        ┆ 0         ┆ 2803.47   │
│ 249227600 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ 11947.53  ┆ 10        ┆ 0         ┆ 2803.47   │
│ 249227600 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ 11947.53  ┆ 10        ┆ 0         ┆ 2803.47   │
│ 249227600 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ 11947.53  ┆ 10        ┆ 0         ┆ 2803.47   │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:

# Asegurate de que foto_mes sea numérica o tipo entero
df = df.with_columns(pl.col("foto_mes").cast(pl.Int64))

# Detectar automáticamente columnas numéricas (ya lo tenías)
numeric_cols = [
    col for col, dtype in df.schema.items()
    if dtype in [pl.Int8, pl.Int16, pl.Int32, pl.Int64, pl.Float32, pl.Float64]
]

# Calcular diferencia último mes - mes anterior por cliente
diff_cols = [
    (pl.col(col) - pl.col(col).shift(1).over("numero_de_cliente")).alias(f"{col}_diff")
    for col in numeric_cols
]

# Agregar estas columnas al df_final
df_final = df_final.with_columns(diff_cols)

df_final.head(10)

shape: (10, 611)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_mcon ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumototal ┆ sumos_dif ┆ lantosefe ┆ ominimo_d │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ _diff     ┆ f         ┆ ctivo_dif ┆ iff       │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ f         ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆ i64       ┆ ---       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 249221323 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249221323 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ 971.88    ┆ 2         ┆ 0         ┆ -2146.59  │
│ 249221323 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ 2987.74   ┆ -1        ┆ 0         ┆ -7413.36  │
│ 249221323 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ -2608.27  ┆ -1        ┆ 0         ┆ 0.0       │
│ 249221323 ┆ 202105   ┆ 1         ┆ 0         ┆ … ┆ 957.25    ┆ 0         ┆ 0         ┆ 2111.4    │
│ 249221323 ┆ 202106   ┆ 1         ┆ 0         ┆ … ┆ 7049.7    ┆ 1         ┆ 0         ┆ 363.63    │
│ 249227600 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249227600 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ 2527.63   ┆ 1         ┆ 0         ┆ 328.44    │
│ 249227600 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ -5043.26  ┆ -4        ┆ 0         ┆ -129.03   │
│ 249227600 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ 2611.43   ┆ 5         ┆ 0         ┆ 703.8     │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [9]:
# Calcular diferencia respecto a dos meses atrás por cliente
diff2_cols = [
    (pl.col(col) - pl.col(col).shift(2).over("numero_de_cliente")).alias(f"{col}_diff2")
    for col in numeric_cols
]

# Agregar estas columnas al df_final
df_final = df_final.with_columns(diff2_cols)

df_final.head(10)

shape: (10, 763)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_mcon ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumototal ┆ sumos_dif ┆ lantosefe ┆ ominimo_d │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ _diff2    ┆ f2        ┆ ctivo_dif ┆ iff2      │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ f2        ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆ i64       ┆ ---       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 249221323 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249221323 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249221323 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ 3959.62   ┆ 1         ┆ 0         ┆ -9559.95  │
│ 249221323 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ 379.47    ┆ -2        ┆ 0         ┆ -7413.36  │
│ 249221323 ┆ 202105   ┆ 1         ┆ 0         ┆ … ┆ -1651.02  ┆ -1        ┆ 0         ┆ 2111.4    │
│ 249221323 ┆ 202106   ┆ 1         ┆ 0         ┆ … ┆ 8006.95   ┆ 1         ┆ 0         ┆ 2475.03   │
│ 249227600 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249227600 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249227600 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ -2515.63  ┆ -3        ┆ 0         ┆ 199.41    │
│ 249227600 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ -2431.83  ┆ 1         ┆ 0         ┆ 574.77    │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [10]:
# 7. Guardar el dataframe resultante en un nuevo CSV
df_final.write_csv("df_confe.csv")

In [11]:
import duckdb

In [12]:
df_final.head(
    
)

shape: (5, 763)
┌───────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ numero_de ┆ foto_mes ┆ active_qu ┆ cliente_v ┆ … ┆ Visa_mcon ┆ Visa_ccon ┆ Visa_cade ┆ Visa_mpag │
│ _cliente  ┆ ---      ┆ arter     ┆ ip        ┆   ┆ sumototal ┆ sumos_dif ┆ lantosefe ┆ ominimo_d │
│ ---       ┆ i64      ┆ ---       ┆ ---       ┆   ┆ _diff2    ┆ f2        ┆ ctivo_dif ┆ iff2      │
│ i64       ┆          ┆ i64       ┆ i64       ┆   ┆ ---       ┆ ---       ┆ f2        ┆ ---       │
│           ┆          ┆           ┆           ┆   ┆ f64       ┆ i64       ┆ ---       ┆ f64       │
│           ┆          ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆           │
╞═══════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 249221323 ┆ 202101   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249221323 ┆ 202102   ┆ 1         ┆ 0         ┆ … ┆ null      ┆ null      ┆ null      ┆ null      │
│ 249221323 ┆ 202103   ┆ 1         ┆ 0         ┆ … ┆ 3959.62   ┆ 1         ┆ 0         ┆ -9559.95  │
│ 249221323 ┆ 202104   ┆ 1         ┆ 0         ┆ … ┆ 379.47    ┆ -2        ┆ 0         ┆ -7413.36  │
│ 249221323 ┆ 202105   ┆ 1         ┆ 0         ┆ … ┆ -1651.02  ┆ -1        ┆ 0         ┆ 2111.4    │
└───────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘